name: Auto-tag on merge to master

on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and create release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.JENKINS }}
          prerelease: false
          files: ''
          body: ''
          automatic_release_tag: true
          tag_name: v${{ steps.get_version.outputs.version }}

