name: Auto-tag on merge to master

on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and create release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.JENKINS }}
          prerelease: true
          files: ''
          body: ''
          tag_name: v${{ steps.get_version.outputs.version }}
          automatic_release_tag: "latest"
          title: "Latest Build"

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::1.0.0"

