name: Tag on Merge
on:
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Increment version number
        id: semver
        uses: juliangruber/semver-action@v1
        with:
          version: ${{ env.VERSION }}
          bump: patch
      
      - name: Create tag
        run: |
          git tag -a v${{ steps.semver.outputs.version }} -m "Tagging release v${{ steps.semver.outputs.version }}"
      
      - name: Push tag
        run: |
          git push origin v${{ steps.semver.outputs.version }}
