name: Auto-tag on merge to master

on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and create/update tag
        uses: JasonEtco/create-or-update-version-tag@v1
        with:
          version: major
          default_bump: minor
          push: true
          push_tag: true
          message: "Bump version to {{version}}"
